---
- name: Add OpenEBS Helm repository
  kubernetes.core.helm_repository:
    name: openebs
    repo_url: https://openebs.github.io/charts
  become: true

- name: Update Helm repositories
  command: helm repo update
  become: true

# Run storage pods only on core master node (control-plane)
- name: Install OpenEBS using Helm
  kubernetes.core.helm:
    name: openebs
    chart_ref: openebs/openebs
    namespace: openebs
    create_namespace: true
    values:
      ndm:
        nodeSelector:
          kubernetes.io/hostname: "{{ core_node_name }}"
        tolerations:
          - operator: "Exists"

      localprovisioner:
        nodeSelector:
          kubernetes.io/hostname: "{{ core_node_name }}"
        tolerations:
          - operator: "Exists"

  become: true

- name: Patch OpenEBS storage class to be default
  shell: |
    kubectl patch storageclass openebs-hostpath \
      -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  become: true
