---
- name: Build UE list from 5G profile (UE18/19/20)
  set_fact:
    ue_list:
      - name: ue1
        imsi: "{{ fiveg.plmn.mcc }}{{ fiveg.plmn.mnc }}{{ fiveg.ues.UE18.imsi_suffix }}"
        dnn: "{{ fiveg.slices | selectattr('name','equalto',fiveg.ues.UE18.slice) | map(attribute='dnn') | first }}"
        ueIp: "{{ srsran_rfsim.ues.UE18.ip }}"
        tx_port: "{{ srsran_rfsim.ues.UE18.ul_port }}"
        rx_port: "{{ srsran_rfsim.ues.UE18.dl_port }}"
      - name: ue2
        imsi: "{{ fiveg.plmn.mcc }}{{ fiveg.plmn.mnc }}{{ fiveg.ues.UE19.imsi_suffix }}"
        dnn: "{{ fiveg.slices | selectattr('name','equalto',fiveg.ues.UE19.slice) | map(attribute='dnn') | first }}"
        ueIp: "{{ srsran_rfsim.ues.UE19.ip }}"
        tx_port: "{{ srsran_rfsim.ues.UE19.ul_port }}"
        rx_port: "{{ srsran_rfsim.ues.UE19.dl_port }}"
      - name: ue3
        imsi: "{{ fiveg.plmn.mcc }}{{ fiveg.plmn.mnc }}{{ fiveg.ues.UE20.imsi_suffix }}"
        dnn: "{{ fiveg.slices | selectattr('name','equalto',fiveg.ues.UE20.slice) | map(attribute='dnn') | first }}"
        ueIp: "{{ srsran_rfsim.ues.UE20.ip }}"
        tx_port: "{{ srsran_rfsim.ues.UE20.ul_port }}"
        rx_port: "{{ srsran_rfsim.ues.UE20.dl_port }}"

- name: Deploy each srsUE pod as separate Helm release
  when: rru == "rfsim"
  kubernetes.core.helm:
    name: "srsue-{{ item.name }}"
    chart_ref: "{{ [repo_dest_abs, 'charts', 'srsue'] | path_join }}"
    release_namespace: "{{ ran_ns }}"
    state: present
    wait: true
    values:
      nodeName: "{{ ran_node_name }}"
      imsi: "{{ item.imsi }}"
      k: "{{ fiveg.security.full_key }}"
      opc: "{{ fiveg.security.opc }}"
      apn: "{{ item.dnn }}"
      ueIp: "{{ item.ueIp }}"
      gnbIp: "{{ srsran_rfsim.broker_ip }}"
      zmq:
        tx_port: "{{ item.tx_port }}"
        rx_port: "{{ item.rx_port }}"
  loop: "{{ ue_list }}"
