- name: Deploy ZMQ broker for multi-UE rfsim
  kubernetes.core.helm:
    name: zmq-broker
    chart_ref: "{{ [repo_dest_abs, 'charts', 'zmq-broker'] | path_join }}"
    release_namespace: "{{ ran_ns }}"
    state: present
    wait: true
    values:
      nodeName: "{{ ran_node_name }}"
      brokerIp: "{{ srsran_rfsim.broker_ip }}"
      gnb:
        dl_port: "{{ srsran_rfsim.gnb_dl_port }}"
        ul_port: "{{ srsran_rfsim.gnb_ul_port }}"
      ues:
        - ip: "{{ srsran_rfsim.ues.UE18.ip }}"
          dl_port: "{{ srsran_rfsim.ues.UE18.dl_port }}"
          ul_port: "{{ srsran_rfsim.ues.UE18.ul_port }}"
        - ip: "{{ srsran_rfsim.ues.UE19.ip }}"
          dl_port: "{{ srsran_rfsim.ues.UE19.dl_port }}"
          ul_port: "{{ srsran_rfsim.ues.UE19.ul_port }}"
        - ip: "{{ srsran_rfsim.ues.UE20.ip }}"
          dl_port: "{{ srsran_rfsim.ues.UE20.dl_port }}"
          ul_port: "{{ srsran_rfsim.ues.UE20.ul_port }}"
