---
duration: "{{ nuttcp_duration | default(30) }}"
sleep: "{{ nuttcp_sleep | default(5) }}"
async_stagger: 0
tcp_bandwidth: "0" # Make sure to NOT add a space between "-Ri" flag and this value
udp_bandwidth: "50M" # Make sure to NOT add a space between "-Ri" flag and this value
tcp_buffer_length: 65536 # Default value of 65536 is probably fine
udp_buffer_length: 1200 # Default of 8192 will cause fragmentation with 1500-byte MTU
do_individual_tests: true
do_simultaneous_tests: true

# Note: downlink scenarios (with -r instead of -t flag) fail to connect for some reason
nuttcp_scenarios:
  - {protocol: "tcp", direction: "up", extra_args: "-t -Ri{{ tcp_bandwidth }} -l {{ tcp_buffer_length }}"}
  # - {protocol: "tcp", direction: "down", extra_args: "-r -Ri{{ tcp_bandwidth }} -l {{ tcp_buffer_length }}"}
  - {protocol: "udp", direction: "up", extra_args: "-u -t -Ri{{ udp_bandwidth }} -l {{ udp_buffer_length }}"}
  # - {protocol: "udp", direction: "down", extra_args: "-u -r -Ri{{ udp_bandwidth }} -l {{ udp_buffer_length }}"}
