core_ns: open5gs
# core_type: open5gs

kopf_image: "r2labuser/kopf-controller:2026w10"
image_pull_policy: Always

probe_image: "r2labuser/ebpf-latency-probe:2026"
exporter_port: "9100"
exporter_path: "/latency"

ue_mapper_limit: "2000"
ue_mapper_url: ""      # optional override
probe_iface: ""        # optional override
latency_mode: "BOTH" # CORE | RAN | BOTH
dry_run: "0"
match_debug: "0"
probe_mode: "gnb" # gnb | upf | both
packet_pairing: "1"
packet_pairer_image: "r2labuser/packet-pairer:2026"
packet_pairer_name: "packet-pairer"
packet_pairer_service_name: "packet-pairer-service"
packet_pairer_metrics_port: "9200"
packet_pairer_metrics_path: "/metrics"
packet_pairer_port: "9201"
