---
monitoring_namespace: monitoring
monitoring_node_label_key: monitoring-node
monitoring_node_label_value: "true"

monitoring_prometheus_chart_version: "51.9.4"
monitoring_grafana_chart_version: "8.6.0"
monitoring_prometheus_stack_release: monitoring
monitoring_grafana_release: grafana
monitoring_prometheus_service_name: monitoring-prometheus

monitoring_interval: "1s"
monitoring_retention: "5d"
monitoring_prometheus_node_port: 30095
monitoring_grafana_node_port: 32005
monitoring_grafana_admin_user: admin
monitoring_grafana_admin_password: monarch-operator

monitoring_scrape_namespaces:
  - open5gs
  - oai
  - oail1
  - free5gc
  - ueransim
  - monitoring

monitoring_persistence_enabled: true
monitoring_mount_storage_device: true
monitoring_storage_class: monitoring-hostpath
monitoring_prometheus_storage_size: 10Gi
monitoring_grafana_storage_size: 2Gi
